'use client';

import React, { useState, useEffect } from 'react';
import { Header } from '@/components/layout/Header';
import { Sidebar } from '@/components/layout/Sidebar';
import { api } from '@/lib/api';
import { IAuditEvent, AuditEventType } from '@netra-shakti/shared-types';
import { History, Search, Shield, AlertCircle, Filter } from 'lucide-react';

export default function AuditLogsPage() {
  const [events, setEvents] = useState<IAuditEvent[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedType, setSelectedType] = useState<string>('');

  const fetchAuditLogs = async () => {
    try {
      setLoading(true);
      const params = new URLSearchParams();
      if (selectedType) params.append('eventType', selectedType);
      params.append('limit', '100');

      const res = await api.get<{ events: IAuditEvent[]; total: number }>(`/audit-events?${params.toString()}`);
      setEvents(res.events || []);
    } catch (err) {
      console.error('Failed to load audit logs:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAuditLogs();
  }, [selectedType]);

  return (
    <div className="min-h-screen bg-cyber-black text-gray-100 flex flex-col">
      <Header />
      <div className="flex flex-1">
        <Sidebar />

        <main className="flex-1 p-8 space-y-6 overflow-y-auto">
          {/* Header */}
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <div>
              <h1 className="text-2xl font-mono font-bold text-white uppercase tracking-wider flex items-center space-x-3">
                <History className="w-6 h-6 text-cyber-cyan" />
                <span>IMMUTABLE SECURITY AUDIT TRAIL</span>
              </h1>
              <p className="text-xs font-mono text-cyber-muted mt-1">
                Forensic recording of every authentication, encryption, decryption, and ledger operation.
              </p>
            </div>

            {/* Filter Dropdown */}
            <div className="flex items-center space-x-2 text-xs font-mono">
              <Filter className="w-4 h-4 text-cyber-muted" />
              <select
                value={selectedType}
                onChange={e => setSelectedType(e.target.value)}
                className="bg-cyber-surface border border-cyber-border rounded px-3 py-2 text-xs font-mono text-white focus:outline-none focus:border-cyber-cyan"
              >
                <option value="">ALL SECURITY EVENTS</option>
                <option value="LOGIN_SUCCESS">LOGIN_SUCCESS</option>
                <option value="LOGIN_FAILED">LOGIN_FAILED</option>
                <option value="DOCUMENT_UPLOADED">DOCUMENT_UPLOADED</option>
                <option value="RECIPIENT_ASSIGNED">RECIPIENT_ASSIGNED</option>
                <option value="DECRYPTION_STARTED">DECRYPTION_STARTED</option>
                <option value="DECRYPTION_COMPLETED">DECRYPTION_COMPLETED</option>
                <option value="INVESTIGATION_ANALYZED">INVESTIGATION_ANALYZED</option>
                <option value="REPORT_EXPORTED">REPORT_EXPORTED</option>
              </select>
            </div>
          </div>

          {/* Audit Table */}
          <div className="bg-cyber-card border border-cyber-border rounded overflow-hidden">
            {loading ? (
              <div className="p-12 text-center text-xs font-mono text-cyber-cyan">
                QUERYING IMMUTABLE AUDIT TRAIL...
              </div>
            ) : events.length === 0 ? (
              <div className="p-16 text-center space-y-3">
                <History className="w-10 h-10 text-cyber-muted mx-auto" />
                <div className="text-sm font-mono font-bold text-white uppercase">
                  NO AUDIT EVENTS RECORDED
                </div>
                <p className="text-xs font-mono text-cyber-muted max-w-sm mx-auto">
                  Audit events are automatically generated by the security kernel for all critical actions.
                </p>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs font-mono">
                  <thead>
                    <tr className="border-b border-cyber-border text-cyber-muted bg-cyber-surface/50">
                      <th className="p-4">TIMESTAMP</th>
                      <th className="p-4">EVENT TYPE</th>
                      <th className="p-4">USER IDENTITY</th>
                      <th className="p-4">ACTION & CONTEXT</th>
                      <th className="p-4">IP / HOST</th>
                      <th className="p-4 text-right">STATUS</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-cyber-border/40">
                    {events.map(evt => (
                      <tr key={evt.id} className="hover:bg-cyber-surface/40">
                        <td className="p-4 text-gray-400">
                          {new Date(evt.createdAt).toLocaleString()}
                        </td>
                        <td className="p-4 font-bold text-cyber-cyan">
                          {evt.eventType}
                        </td>
                        <td className="p-4">
                          <div className="font-bold text-white">{evt.user?.displayName || 'SYSTEM / ANONYMOUS'}</div>
                          {evt.user && <div className="text-[10px] text-gray-400">@{evt.user.username} ({evt.user.role})</div>}
                        </td>
                        <td className="p-4 text-gray-300 max-w-md">
                          {evt.action}
                        </td>
                        <td className="p-4 text-gray-400 text-[11px]">
                          {evt.ipAddress || '127.0.0.1'}
                        </td>
                        <td className="p-4 text-right">
                          <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${evt.status === 'SUCCESS' ? 'bg-cyber-green/15 text-cyber-green border border-cyber-green/30' : 'bg-cyber-red/15 text-cyber-red border border-cyber-red/30'}`}>
                            {evt.status}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </main>
      </div>
    </div>
  );
}
